# Generated by Django 6.0.4 on 2026-04-25 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('skills_found', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('jd_match_percent', models.FloatField(default=0.0)),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
